/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CLASES.Cliente;
import CLASES.Cotizacion;
import CLASES.Usuario;
import CLASES.Vehiculo;
import CLASES.Venta;
import GESTION.GestionCotizacion;
import GESTION.GestionVenta;
import GESTION.GestionVehiculo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmAprobarCotizacion extends javax.swing.JFrame {

    private GestionCotizacion gCot;
    private GestionVenta gVen;
    private GestionVehiculo gVeh;

    public frmAprobarCotizacion(GestionCotizacion gCot, GestionVenta gVen, GestionVehiculo gVeh) {
        initComponents();
        this.gCot = gCot;
        this.gVen = gVen;
        this.gVeh = gVeh;
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        configurarTabla();
        cargarPendientes();
        setLocationRelativeTo(null);
    }
    
    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[][]{},
            new String[]{
                "Código", "Cliente", "Vehículo", "Monto Total", "Fecha"
            }
        );
        tblPendientes.setModel(modelo);
    }
    
    private void cargarPendientes() {
        DefaultTableModel modelo = (DefaultTableModel) tblPendientes.getModel();
        modelo.setRowCount(0);  

        Cotizacion[] lista = gCot.obtenerCotizacionesPendientes();

        for (Cotizacion c : lista) {
            if (c != null) {
                modelo.addRow(new Object[]{
                    c.getCodigo(),
                    c.getCliente().getNombres(),
                    c.getVehiculo().getMarca() + " " + c.getVehiculo().getModelo(),
                    c.getMontoTotal(),
                    c.getFecha()
                });
            }
        }
    }
    
    private Cotizacion getCotizacionSeleccionada() {
        int fila = tblPendientes.getSelectedRow();
        if (fila == -1) {
            mensaje("Seleccione una cotización");
            return null;
        }
        String codigo = tblPendientes.getValueAt(fila, 0).toString();
        return gCot.buscarPorCodigo(codigo);
    }

    private void mensaje(String txt) {
        JOptionPane.showMessageDialog(this, txt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPendientes = new javax.swing.JTable();
        lblListado = new javax.swing.JLabel();
        btnAprobar = new javax.swing.JButton();
        btnRechazar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPendientes);

        lblListado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblListado.setText("Cotizaciones Pendientes");

        btnAprobar.setText("Aprobar");
        btnAprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprobarActionPerformed(evt);
            }
        });

        btnRechazar.setText("Rechazar");
        btnRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechazarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblListado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAprobar)
                .addGap(44, 44, 44)
                .addComponent(btnRechazar)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblListado, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAprobar)
                    .addComponent(btnRechazar))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void aprobarCotizacion() {
        Cotizacion c = getCotizacionSeleccionada();
        if (c != null) {
            c.setEstado("APROBADA");
            mensaje("Cotización aprobada");
            cargarPendientes();
        }
    }

    private void rechazarCotizacion() {
        Cotizacion c = getCotizacionSeleccionada();
        if (c != null) {
            c.setEstado("RECHAZADA");
            mensaje("Cotización rechazada");
            cargarPendientes();
        }
    }

    private void abrirRegistrarVenta() {
        Cotizacion c = getCotizacionSeleccionada();
        if (c == null) return;

        if (!c.getEstado().equals("APROBADA")) {
            mensaje("Debe aprobar la cotización antes de registrar la venta.");
            return;
        }

        new frmRegistrarVenta(c, gVen, gVeh).setVisible(true);
    }
    
    
    private void btnAprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprobarActionPerformed
        Cotizacion c = getCotizacionSeleccionada();
        if (c == null) return;

    
        c.setEstado("APROBADA");

    
        String codigoVenta = gVen.generarCodigoVenta();
        Venta v = new Venta(codigoVenta, c, c.getMontoTotal());

        gVen.registrar(v);

    
        Vehiculo veh = c.getVehiculo();
        veh.setEstado("VENDIDO");
        gVeh.actualizar(veh);

    
        mensaje("Cotización aprobada y venta registrada.\nCódigo venta: " + codigoVenta);

    
        cargarPendientes();

    
        new frmRegistrarVenta(c, gVen, gVeh).setVisible(true);
    }//GEN-LAST:event_btnAprobarActionPerformed

    private void btnRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechazarActionPerformed
        Cotizacion c = getCotizacionSeleccionada();
        if (c != null) {
            c.setEstado("RECHAZADA");
            mensaje("Cotización rechazada");
            cargarPendientes();
            new frmRegistrarVenta(c, gVen, gVeh).setVisible(true);
        }
    }//GEN-LAST:event_btnRechazarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

    
        GestionCotizacion gCot = new GestionCotizacion();
        GestionVenta gVen = new GestionVenta();
        GestionVehiculo gVeh = new GestionVehiculo();

   
        Vehiculo v = new Vehiculo(
            "V001", "Toyota", "Corolla", "Plata",
            2023, "Sedan", 56000, "DISPONIBLE"
        );
        gVeh.registrar(v);

        Cliente cli = new Cliente(
            "12345678", "Juan", "Pérez",
            "Av. Lima 123", "987654321", "juan@mail.com"
        );

        Usuario ven = new Usuario(
            "87654321", "Carlos", "Vargas",
            "cvargas", "123", "VENDEDOR"
        );

        Cotizacion cot = new Cotizacion(
            "COT0001",
            cli,
            ven,
            v,
            null,        
            "10/02/2025"
        );
        cot.setEstado("PENDIENTE");


        gCot.registrar(cot);

        frmAprobarCotizacion frm = new frmAprobarCotizacion(gCot, gVen, gVeh);
        frm.setVisible(true);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprobar;
    private javax.swing.JButton btnRechazar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListado;
    private javax.swing.JTable tblPendientes;
    // End of variables declaration//GEN-END:variables
}
