/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import CLASES.Usuario;
import GESTION.GestionClientes;
import GESTION.GestionCotizacion;
import GESTION.GestionPromocion;
import GESTION.GestionUsuario;
import GESTION.GestionVehiculo;
import GESTION.GestionVenta;
import Utilitario.EscritorioPersonalizado;
import javax.swing.UIManager;
/**
 *
 * @author Anahy
 */
public class frmPrincipalVendedor extends javax.swing.JFrame {

    private EscritorioPersonalizado escritorio;
    private GestionVehiculo gv = new GestionVehiculo();
    private Usuario vendedorActual;
    private GestionClientes gc = new GestionClientes();
    private GestionPromocion gp = new GestionPromocion();
    private GestionUsuario gu = new GestionUsuario();
    private GestionVenta gven = new GestionVenta();
    private GestionCotizacion gcot = new GestionCotizacion();
    
    
    public frmPrincipalVendedor(Usuario vendedor) {
        initComponents();
        escritorio = new EscritorioPersonalizado();
        this.setContentPane(escritorio);
        
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Vendedor");
        this.vendedorActual = vendedor;
        escritorio = new EscritorioPersonalizado();
        this.setContentPane(escritorio);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnClientes = new javax.swing.JMenu();
        mnItemGestionClientes = new javax.swing.JMenuItem();
        mnConsultarVehiculos = new javax.swing.JMenu();
        mnItemConsultarEstado = new javax.swing.JMenuItem();
        mnCotizaciones = new javax.swing.JMenu();
        mnItemCotizacion = new javax.swing.JMenuItem();
        mnItemAprobarCotizacion = new javax.swing.JMenuItem();
        mnItemRegistroVentaPago = new javax.swing.JMenuItem();
        mnReportes = new javax.swing.JMenu();
        mnItemGestionReportes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setToolTipText("");

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1251, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        mnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/empleados.png"))); // NOI18N
        mnClientes.setText("Clientes");
        mnClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mnItemGestionClientes.setText("Gestión de clientes");
        mnItemGestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemGestionClientesActionPerformed(evt);
            }
        });
        mnClientes.add(mnItemGestionClientes);

        jMenuBar1.add(mnClientes);

        mnConsultarVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/lupa.png"))); // NOI18N
        mnConsultarVehiculos.setText("Consultar vehículos");
        mnConsultarVehiculos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mnItemConsultarEstado.setText("Consultar estado de  los vehículos");
        mnItemConsultarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemConsultarEstadoActionPerformed(evt);
            }
        });
        mnConsultarVehiculos.add(mnItemConsultarEstado);

        jMenuBar1.add(mnConsultarVehiculos);

        mnCotizaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/cotizacion.png"))); // NOI18N
        mnCotizaciones.setText("Cotización de vehiculos");
        mnCotizaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mnItemCotizacion.setText("Cotización de vehiculos disponibles");
        mnItemCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemCotizacionActionPerformed(evt);
            }
        });
        mnCotizaciones.add(mnItemCotizacion);

        mnItemAprobarCotizacion.setText("Aprobar Cotización");
        mnItemAprobarCotizacion.setToolTipText("");
        mnItemAprobarCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemAprobarCotizacionActionPerformed(evt);
            }
        });
        mnCotizaciones.add(mnItemAprobarCotizacion);

        mnItemRegistroVentaPago.setText("Registro de venta y pago");
        mnItemRegistroVentaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemRegistroVentaPagoActionPerformed(evt);
            }
        });
        mnCotizaciones.add(mnItemRegistroVentaPago);

        jMenuBar1.add(mnCotizaciones);

        mnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/reportes.png"))); // NOI18N
        mnReportes.setText("Reportes");
        mnReportes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mnItemGestionReportes.setText("Gestión de reportes");
        mnItemGestionReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemGestionReportesActionPerformed(evt);
            }
        });
        mnReportes.add(mnItemGestionReportes);

        jMenuBar1.add(mnReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItemGestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemGestionClientesActionPerformed
        frmGestionClientes frm = new frmGestionClientes();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_mnItemGestionClientesActionPerformed

    private void mnItemCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemCotizacionActionPerformed
        frmCotizacion frm = new frmCotizacion(vendedorActual,gv,gc,gp,gu,gcot);
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_mnItemCotizacionActionPerformed

    private void mnItemGestionReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemGestionReportesActionPerformed
        
    }//GEN-LAST:event_mnItemGestionReportesActionPerformed

    private void mnItemConsultarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemConsultarEstadoActionPerformed
        frmBuscarEstado frm = new frmBuscarEstado(gv);
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_mnItemConsultarEstadoActionPerformed

    private void mnItemAprobarCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemAprobarCotizacionActionPerformed
        frmAprobarCotizacion frm = new frmAprobarCotizacion(gcot, gven, gv); 
        frm.setVisible(true);
    }//GEN-LAST:event_mnItemAprobarCotizacionActionPerformed

    private void mnItemRegistroVentaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemRegistroVentaPagoActionPerformed
        frmAprobarCotizacion frm = new frmAprobarCotizacion(gcot, gven, gv); 
        frm.setVisible(true);
    }//GEN-LAST:event_mnItemRegistroVentaPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.windowsLookAndFeel");
        }catch(Exception e){
            
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Usuario vendedor = new Usuario("56789", "Sebastián", "", "qwer", "56789", "VENDEDOR");

            
            new frmPrincipalVendedor(vendedor).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnClientes;
    private javax.swing.JMenu mnConsultarVehiculos;
    private javax.swing.JMenu mnCotizaciones;
    private javax.swing.JMenuItem mnItemAprobarCotizacion;
    private javax.swing.JMenuItem mnItemConsultarEstado;
    private javax.swing.JMenuItem mnItemCotizacion;
    private javax.swing.JMenuItem mnItemGestionClientes;
    private javax.swing.JMenuItem mnItemGestionReportes;
    private javax.swing.JMenuItem mnItemRegistroVentaPago;
    private javax.swing.JMenu mnReportes;
    // End of variables declaration//GEN-END:variables
}
