/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Utilitario.EscritorioPersonalizado;
import javax.swing.UIManager;

public class frmPrincipalAdministrador extends javax.swing.JFrame {
    private EscritorioPersonalizado escritorio;
   
    
    
    public frmPrincipalAdministrador() {
        initComponents();
        escritorio = new EscritorioPersonalizado();
        this.setContentPane(escritorio);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Administrador");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBarAdministrador = new javax.swing.JMenuBar();
        mnEmpleados = new javax.swing.JMenu();
        mnItemRegistrarEmpleado = new javax.swing.JMenuItem();
        mnVehiculos = new javax.swing.JMenu();
        mnItemGestionVehiculos = new javax.swing.JMenuItem();
        mnPromociones = new javax.swing.JMenu();
        mnItemGestionPromociones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        mnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/empleados.png"))); // NOI18N
        mnEmpleados.setText("Empleados");
        mnEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mnItemRegistrarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnItemRegistrarEmpleado.setText("Gestión de empleados");
        mnItemRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemRegistrarEmpleadoActionPerformed(evt);
            }
        });
        mnEmpleados.add(mnItemRegistrarEmpleado);

        menuBarAdministrador.add(mnEmpleados);

        mnVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/vehiculo.png"))); // NOI18N
        mnVehiculos.setText("Vehículos");
        mnVehiculos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mnItemGestionVehiculos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnItemGestionVehiculos.setText("Gestion de vehículos");
        mnItemGestionVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemGestionVehiculosActionPerformed(evt);
            }
        });
        mnVehiculos.add(mnItemGestionVehiculos);

        menuBarAdministrador.add(mnVehiculos);

        mnPromociones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/descuento.png"))); // NOI18N
        mnPromociones.setText("Promociones");
        mnPromociones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mnItemGestionPromociones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnItemGestionPromociones.setText("Gestión de promociones");
        mnItemGestionPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemGestionPromocionesActionPerformed(evt);
            }
        });
        mnPromociones.add(mnItemGestionPromociones);

        menuBarAdministrador.add(mnPromociones);

        setJMenuBar(menuBarAdministrador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItemRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemRegistrarEmpleadoActionPerformed
        frmGestionEmpleados frm = new frmGestionEmpleados();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_mnItemRegistrarEmpleadoActionPerformed

    private void mnItemGestionVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemGestionVehiculosActionPerformed
        frmGestionVehiculos frm = new frmGestionVehiculos();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_mnItemGestionVehiculosActionPerformed

    private void mnItemGestionPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemGestionPromocionesActionPerformed
        frmPromocion frm = new frmPromocion();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_mnItemGestionPromocionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        
        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.windowsLookAndFeel");
        }catch(Exception e){
            
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipalAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBarAdministrador;
    private javax.swing.JMenu mnEmpleados;
    private javax.swing.JMenuItem mnItemGestionPromociones;
    private javax.swing.JMenuItem mnItemGestionVehiculos;
    private javax.swing.JMenuItem mnItemRegistrarEmpleado;
    private javax.swing.JMenu mnPromociones;
    private javax.swing.JMenu mnVehiculos;
    // End of variables declaration//GEN-END:variables
}
